### ISSUE TITLE
Instantiating AlgorithmManager

### ISSUE THREAD

**Issue by ingalless** [web-token/jwt-doc#11]
[On this page of the docs](https://web-token.spomky-labs.com/components/algorithm-management-jwa) an example is given of creating a Jose\Component\Core\AlgorithmManager, like the below

`$algorithm_manager = new AlgorithmManager([
    new PS256(),
    new ES512(),
]);`

However, the constructor function for Jose\Component\Core\AlgorithmManager is private. Shouldn't this use the public static "create" method, like below?
`$algorithm_manager = AlgorithmManager::create([ new PS256(), new ES512(), ])`

Hope that makes sense, let me know if you need any more info!

**Comment by Spomky** [comment]
Hi @ingalless,

I recently updated the documentation. This syntax will correspond to the v2.0 to come. The one with the create method is the valid way for v1.x and will be marked as obsolete soon. 

I have to find a way to manage the doc versions a better way. It is difficult to differentiate the feature / proper method in the current configuration.

**Comment by Spomky** [comment]
I’ve created new branches of the documentation.
Should be ok now.
Feel free to open this issue again if not.

**Comment by ingalless** [comment]
@Spomky Looks perfect!
Glad it's helped someone else out too.

Thanks for this library, it's great! 👍

**Comment by Spomky** [comment]
You’re welcome!
I think it is relevant to create a branch for all minor versions i.e. v1.0, 1.1… and avoid messages like `This feature was introduced in version 1.x`.

**Comment by ingalless** [comment]
That seems a good idea! Although mentioning something like `new to 1.x is...` in the docs could be a nice addition for developers unaware of new features?
An example from [this page](https://web-token.spomky-labs.com/components/key-jwk-and-key-set-jwkset/key-management#octet-string) below 

> **New to version 1.1**, If you already have a shared secret, you can use it to create an oct key

The English there isn't great, but I hope it conveys the idea.

It might be a good idea to include an upgrade guide for major releases too? ([Example](https://laravel.com/docs/5.7/upgrade))
If anything, it will save me some confusion when I upgrade to 2.x in future and have the inverse of the issue I've just faced 😆

**Comment by Spomky** [comment]
Ok I will try to improve that way.
Normally the upgrade from v1.x to v2.0 will be smooth. The idea is to mark methods/classes/… as deprecated in v1.x with a message for replacement. When you have no deprecation message, then you will be able to upgrade without any change but the package versions.
