### ISSUE TITLE
JWS "After" now includes several deprecated classes

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-token/jwt-doc#12]
Migrating from JOSE, the JWS loading "After" now includes deprecated classes that I can find no alternative for. `CompactSerializer` is deprecated, but there is no guidance on what replacement to use. I think `JSONFlattenedSerializer` as I'm using that to create(?) my JWS, but that expects a `Jose\Component\Core\Converter\JsonConverter` (deprecated), not a `Jose\Component\Core\Util\JsonConverter`.

Should I actually be trying to use 2.0 instead?

**Comment by Spomky** [comment]
Hi @moderndeveloperllc,

`CompactSerializer` is not deprecated (and there no reason to deprecate it).
I am working on a PR to prepare the removal of `Jose\Component\Core\Converter\JsonConverter`. All objects that use it will be modify to accept a `null` value indicating the new internal `Jose\Component\Core\Util\JsonConverter` has to be used.
As an example, youcan see [the new __constructor method](https://github.com/web-token/jwt-framework/blob/JsonConverter/src/Component/Signature/JWSBuilder.php#L58) for the `JWSBuilder` class.
The 2.0 branch is not yet ready to by used, but you can try to play with it.

I will update the doc when this PR is ready to be merged

**Comment by moderndeveloperllc** [comment]
Sorry, I think I meant `StandardConverter`. I see that you are changing the signature to not require that specific JSON class. I'll close.

**Comment by fidding** [comment]
just like this

```php
    // v1.3
    $jsonConverter = new \Jose\Component\Core\Util\JsonConverter();

    $jwsBuilder = new Jose\Component\Signature\JWSBuilder(
        null,
        $algorithmManager
    );
```
