### ISSUE TITLE
Migration documentation assumes Symfony configuration

### ISSUE THREAD

**Issue by mpwaldhorst** [web-token/jwt-doc#13]
As far as I can see in the migration documentation with regards to the usage of JKUFactory the assumption is made that one uses Symfony.

https://web-token.spomky-labs.com/migration/from-spomky-labs-jose/key-sets-jwkset#jkufactory-x-5-ufactory

There does not seem to be any information on how to use these classes in non Symfony projects.

It would be great if more information on this can be provided.

**Comment by Spomky** [comment]
That’s right. This section of the doc should be updated.
To use the `JKUFactory`, you need:

* [An Httplug client](http://docs.php-http.org/en/latest/clients.html),
* [A message factory](http://docs.php-http.org/en/latest/message/message-factory.html)

When done, you can create an instance of the [JKUFactory class](https://github.com/web-token/jwt-framework/blob/v1.3/src/Component/KeyManagement/JKUFactory.php#L28) (first argument should be `null` with v1.3.5+).
Then you can retrieve the JWKSet using the method `loadFromUrl`.

I will take time to update the doc. Let me know if you need anything else.

**Comment by taghreedalshammari** [comment]
Hello, Any updates regarding this? 
Is there an implemented example?

after getting the jwkset from the URL, how will be the verification done?

in old version we use


```
$jws = $loader->loadAndVerifySignatureUsingKeySet(
$input,
$jwk,
['RS256'],
$signature_index
);
```
