### ISSUE TITLE
using ES256 alg for Apple Push notifications ask me for x y and crv ? 

### ISSUE THREAD

**Issue by jrm0695** [web-token/jwt-doc#14]
I'm trying to use the librairy to implement a php script that refresh a JWT token that will be used to send push notification to Apple APN. Apple takes only into account ES256. I followed this guide to implement the script : https://web-token.spomky-labs.com/components/signed-tokens-jws/jws-creation but when I change HS256 to Apple ES256, the librairy throws an exception at build() function saying I need to give x, y and crv parameters in my key. Though, I have no idea about what these params are, Apple does not talk about any of these parameters. 
So I would like to know what are these missing parameters and how can I find them ?

**Comment by jrm0695** [comment]
Sorry its my fault, "key" from Apple website must be transformed into a JWK containing x y and crv params, in JSON format. Thank you @Spomky for your answer on StackOverflow :)

**Comment by Spomky** [comment]
No worries. The package should be installer with web-token/core. It is now fixed in v1.3.8.
