### ISSUE TITLE
Document link is not working

### ISSUE THREAD

**Issue by faizanktk** [web-token/jwt-doc#23]
Hi,
This link https://web-token.spomky-labs.com/components/algorithm-management-jwa is not working. Will you fix this
Thanks

**Comment by Spomky** [comment]
Hi @faizanktk,

Thank you for reporting me this broken link.
On which page did you found it ?

The correct url is https://web-token.spomky-labs.com/the-components/algorithm-management-jwa

**Comment by faizanktk** [comment]
Thanks.
I found it here and i have the same issue
https://github.com/web-token/jwt-doc/issues/11

By the way i did not find  https://web-token.spomky-labs.com/the-components/algorithm-management-jwa or Component link in Left menu.
