### ISSUE TITLE
No replacement for Jose\Component\Core\Converter\StandardConverter

### ISSUE THREAD

**Issue by chris-baur** [web-token/jwt-doc#30]
Situation:
- trying to use apple APN [link](https://github.com/ZhukV/AppleApnPush/blob/master/docs/index.md)
- uses this repo for dealing with JWT

Issue:
- At some point in the process it tries to generate a signature
    `return new WebTokenJwtSignatureGenerator`
- This class uses the missing class in constructor
```
        $this->jsonConverter = new StandardConverter();
        $this->jwsBuilder = new JWSBuilder($this->jsonConverter, AlgorithmManager::create([new ES256()]));
        $this->serializer = new CompactSerializer($this->jsonConverter);
```

Server on php 7.4
if there is no replacement, how is this supposed to work?[link to some version changes](https://web-token.spomky-labs.com/migration-1/migration/from-v1.x-to-v2.0)

**Comment by Spomky** [comment]
Hi,

You will find the source code of [this object here](https://github.com/web-token/jwt-framework/blob/v1.3.10/src/Component/Core/Converter/StandardConverter.php).

As you may notice, it just calls `json_decode` and `json_encode`, that’s why it has been removed.
