### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by 64knl** [web-token/jwt-doc#36]
In this section the example key created has 'use' defined as 'sig', but I believe it should be 'enc':
https://web-token.spomky-labs.com/the-easy-way/easy#jwe-creation-and-decryption

Relevant parts:

$jwk = new JWK(['use' => '**sig**']);
$jwe = Build::jwe() // We build a JWE
    ->encrypt($jwk) // Compute the token with the given JWK (public key)

**Comment by Spomky** [comment]
Hi @NotFoundDC,

You are right. I've just updated the doc.
Many thanks!
