### ISSUE TITLE
Argument 1 passed to Jose\Component\Core\Util\JsonConverter::decode() must be of the type string, null given, called in /var/www/html/sghealth/server/vendor/web-token/jwt-easy/Decrypt.php on line 117

### ISSUE THREAD

**Issue by yatendra121** [web-token/jwt-doc#38]
$jwt = Load::jwe($jwe) // We want to load and decrypt the token in the variable $token
    ->algs(['ECDH-ES+A128KW']) // The key encryption algorithms allowed to be used
    ->encs(['A256CBC-HS512']) // The content encryption algorithms allowed to be used
    ->key($jwk) // Key used to decrypt the token
    ->run()

**Comment by masc-it** [comment]
same problem.. any fix?

**Comment by apksundar1980** [comment]
Dear Sir/Madam,

We are facing this issue.
is there any fix?
Please let me know, once this issue resolved.

Thank you,
Sundar

**Comment by apksundar1980** [comment]
FYI. JWE id_token is generated by third party.
is not able to decrypt. getting payload null error.

**Comment by Spomky** [comment]
Hi,

This error usually occurs when you are passing a JWE, but the decryption key is not part of the key set.

Would you please send me som sample data for helping me to understand the issue?

**Comment by apksundar1980** [comment]
Hi Spomky,

Thanks for the quick response.

Here are the sample data

 $id_token = 'eyJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOi..';

$serializer = new CompactSerializer(); 
   $jwe_object = $serializer->unserialize($id_token);
$success = $jweDecrypter->decryptUsingKey($jwe_object,$jwk_key,0);

Below are the key
I hided d = private key below 
$jwk_key = JWKFactory::createFromValues(
                
                [        
                    'kty' => 'EC',
                    'use' => 'enc',
                    'crv' => 'P-521',
                    'kid' => '',
                  
                    'alg' => "ECDH-ES+A192KW",
                    'd' => '' "
                   
                ]);
Please let me know any other details you need.
above program i tried

$keyEncryptionAlgorithmManager = new AlgorithmManager([
            new ECDHESA192KW(),
        ]);

        // The content encryption algorithm manager with the A256CBC-HS256 algorithm.
        $contentEncryptionAlgorithmManager = new AlgorithmManager([
            new A256CBCHS512(),
        ]);

        // The compression method manager with the DEF (Deflate) method.
        $compressionMethodManager = new CompressionMethodManager([
            new Deflate(),
        ]);

        $headerCheckerManager = new HeaderCheckerManager(
            [
                new AlgorithmChecker(['ES512']), // We check the header "alg" (algorithm)
            ],
            [
                new JWSTokenSupport(), // Adds JWS token type support
            ]
        );

        $jweDecrypter = new JWEDecrypter(
            $keyEncryptionAlgorithmManager,
            $contentEncryptionAlgorithmManager,
            $compressionMethodManager
        );

**Comment by apksundar1980** [comment]
FYI. this id_token is able to decrypt with python library code

**Comment by apksundar1980** [comment]
is there any error in constructing key ? any format error?

**Comment by apksundar1980** [comment]
@Spomky  Please let me know why the payload not able to decrypt. error in key? Thanks

**Comment by apksundar1980** [comment]
any updates?

**Comment by apksundar1980** [comment]
$result = $key_encryption_algorithm->decryptKey($recipientKey, $recipient->getEncryptedKey(), $completeHeader); This line getting memory allocation errror
Allowed memory size of 134217728 bytes exhausted (tried to allocate 132124672 bytes)

**Comment by apksundar1980** [comment]
The algorithm EC-DH-CS * are not recommented unless used with OKP key.
I can see the above instructions in the documentation

ECDH-ES+A192KW - This key encryption is not recommented with EC Key? because i used EC key type.

Please let me know above correct. because of that decrypt not working?
